#pragma once

#include "../../Cmr/Cmr.h"
#include "../Actor/Actor.h"

using namespace Core::Cmr::Types;
using namespace Core::Cmr::ExtendedTypes;

namespace Core
{
	namespace SDK
	{
		class Player : public Actor
		{
		public:
			virtual void _func261();
			virtual void _func262();
			virtual void SetSleeping(bool);
			virtual void SetSprinting(bool);
			virtual void _func265();
			virtual void _func266();
			virtual void _func267();
			virtual void _func268();
			virtual void _func269();
			virtual float GetSpeed(void);
			virtual void SetSpeed(float);
			virtual float GetJumpPower(void);
			virtual void _func273();
			virtual void _func274();
			virtual void _func275();
			virtual void _func276();
			virtual void Travel(float, float, float);
			virtual void ApplyFinalFriction(float, bool);
			virtual void UpdateWalkAnim(void);
			virtual void _func280();
			virtual void AIStep(void);
			virtual void PushActors(void);
			virtual void LookAt(Actor*, float, float);
			virtual bool IsLookingAtAnEntity(void);
			virtual void _func285();
			virtual bool CheckSpawnObstruction(void);
			virtual float GetAttackAnim(float);
			virtual float GetItemUseDuration(void);
			virtual float GetItemUseStartupProgress(void);
			virtual float GetItemUseIntervalProgress(void);
			virtual int GetItemuseIntervalAxis(void);
			virtual int GetTimeAlongSwing(void);
			virtual void _func293();
			virtual float GetMaxHeadXRot(void);
			virtual Actor GetLastHurtByMob(void);
			virtual void SetLastHurtByMob(Actor*);
			virtual void _func297();
			virtual void _func298();
			virtual void _func299();
			virtual void _func300();
			virtual void _func301();
			virtual void DoHurtTarget(Actor*);
			virtual void _func303();
			virtual void LeaveCaravan(void);
			virtual void JoinCaravan(Actor*);
			virtual bool HasCaravanTail(void);
			virtual uint64_t GetCaravanHead(void);
			virtual int GetArmorValue(void);
			virtual int GetArmorCoverPercentage(void);
			virtual void _func310();
			virtual void _func311();
			virtual void _func312();
			virtual void _func313();
			virtual void _func314();
			virtual void _func315();
			virtual void _func316();
			virtual void UpdateEquipment(void);
			virtual void ClearEquipment(void);
			virtual void _func319();
			virtual void _func320();
			virtual void _func321();
			virtual void _func322();
			virtual void _func323();
			virtual void DropEquipmentOnDeath(void);
			virtual void _func325();
			virtual void _func326();
			virtual void _func327();
			virtual void _func328();
			virtual void CreateAIGoals(void);
			virtual void _func330();
			virtual void SetItemSlot(int, class ItemStack const&);
			virtual void SetTransitioningSitting(bool);
			virtual void AttackAnimation(Actor*, bool);
			virtual void _func334();
			virtual void _func335();
			virtual void _func336();
			virtual void _func337();
			virtual void AscendLadder(void);
			virtual void AscendScaffolding(void);
			virtual void DescendScaffolding(void);
			virtual void DropContainer(void);
			virtual void _func342();
			virtual void _func343();
			virtual void JumpFromGround(void);
			virtual void _func345();
			virtual void _func346();
			virtual void _func347();
			virtual void _func348();
			virtual void _func349();
			virtual void DropBags(void);
			virtual void TickDeath(void);
			virtual void UpdateGliding(void);
			virtual void _func353();
			virtual void _func354();
			virtual void DestroyRegion(void);
			virtual void SuspendRegion(void);
			virtual void _func357();
			virtual bool _fireWillChangeDimension(void);
			virtual void _fireDimensionChanged(void);
			virtual void _func360();
			virtual void TickWorld(void);
			virtual void _func362();
			virtual void _func363();
			virtual void MoveView(void);
			virtual void _func365();
			virtual void _func366();
			virtual void _func367();
			virtual void _func368();
			virtual void Respawn(void);
			virtual void _func370();
			virtual void ResetPos(bool);
			virtual void _func372();
			virtual bool HasResource(int);
			virtual void CompleteUsingItem(void);
			virtual void SetPermissions(int);
			virtual void StartDestroying(void);
			virtual void StopDestroying(void);
			virtual void _func378();
			virtual void _func379();
			virtual void _func380();
			virtual bool CanOpenContainerScreen(void);
			virtual void _func382();
			virtual void _func383();
			virtual void _func384();
			virtual void _func385();
			virtual void _func386();
			virtual void _func387();
			virtual void _func388();
			virtual void _func389();
			virtual void StartSleepInBed(Vector3 const&);
			virtual void StopSleepInBed(bool, bool);
			virtual bool CanStartSleepInBed(void);
			virtual int GetSleepTimer(void);
			virtual int GetPreviousTickSleepTimer(void);
			virtual void _func395();
			virtual void _func396();
			virtual void _func397();
			virtual void _func398();
			virtual void _func399();
			virtual void _func400();
			virtual void _func401();
			virtual void _func402();
			virtual void SetPlayerGameType(int);
			virtual void CriticalHit(Actor&);
			virtual void _func405();
			virtual void _func406();
			virtual void SendEventPacket(class EventPacket);
			virtual void AddExperience(int);
			virtual void AddLevels(int);
			virtual void _func410();
			virtual void _func411();
			virtual void _func412();
			virtual void _func413();
			virtual void DeleteContainerManager(void);
			virtual void SetFieldOfViewModifier(float);
			virtual void _func416();
			virtual void _func417();
			virtual void _func418();
			virtual void _func419();
			virtual void _func420();
			virtual void StartCooldown(class Item const*);
			virtual void _func422();
			virtual void _func423();
			virtual void _func424();
			virtual void _func425();
			virtual void _func426();
			virtual void _func427();
			virtual void _func428();
			virtual void _func429();
			virtual void _func430();
			virtual void _func431();
			virtual void _func432();
		};
	}
}